version: 1.2
workflows:
  - subclass: CWL
    primaryDescriptorPath: /Dockstore.cwl
    testParameterFiles:
      - /inp_job.yml
    authors:
      - name: Linkun Gao
        email: gaolinkun123@gmail.com
